<?php

namespace inseadBundle\Repository;

/**
 * createTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class createTripRepository extends \Doctrine\ORM\EntityRepository
{
}
